using System.Xml.Linq;
using Xunit;

namespace Ucl.Integration.Tests;

/// <summary><c>ucl export-csproj</c>: IDE project files for the first cell, written only to <c>--out</c>.</summary>
public sealed class ExportCsprojTests
{
    private static string Prop(XDocument doc, string name) => doc.Root!.Elements("PropertyGroup").Elements(name).Single().Value;

    /// <summary>One csproj per assembly with defines, sources, editor references and project references, plus a slnx.</summary>
    [Fact]
    public void Writes_projects_and_solution()
    {
        using var temp = new TempDir();
        var project = Path.Combine(temp.Path, "MyGame");
        TempDir.Copy(Path.Combine(Repo.Fixtures, "asmdef-ref-by-name"), project);
        var outDir = Path.Combine(temp.Path, "ide");

        var (exit, stdout, stderr) = Cli.Run(new TestEnvironment(temp.Path), "export-csproj", project, "--out", outDir, "--cache-dir", Path.Combine(temp.Path, "c"));

        Assert.True(exit == 0, stdout + stderr);
        var core = XDocument.Load(Path.Combine(outDir, "Game.Core.csproj"), LoadOptions.None);
        var gameplay = XDocument.Load(Path.Combine(outDir, "Game.Gameplay.csproj"), LoadOptions.None);
        var solution = XDocument.Load(Path.Combine(outDir, "MyGame.slnx"));

        foreach (var doc in new[] { core, gameplay, solution })
        {
            Assert.Contains("Generated by `ucl export-csproj`", Assert.IsType<XComment>(doc.FirstNode).Value, StringComparison.Ordinal);
        }

        Assert.Equal("Microsoft.NET.Sdk", gameplay.Root!.Attribute("Sdk")!.Value);
        Assert.Equal("netstandard2.1", Prop(gameplay, "TargetFramework"));
        Assert.Equal("false", Prop(gameplay, "EnableDefaultCompileItems"));
        Assert.Equal("true", Prop(gameplay, "NoStdLib"));
        Assert.Equal("true", Prop(gameplay, "DisableImplicitFrameworkReferences"));
        Assert.Equal("9.0", Prop(gameplay, "LangVersion"));
        var defines = Prop(gameplay, "DefineConstants").Split(';');
        Assert.Contains("UNITY_EDITOR", defines);
        Assert.Contains("UNITY_6000_0_OR_NEWER", defines);
        Assert.Contains("CS0169", Prop(gameplay, "NoWarn"), StringComparison.Ordinal);

        var compile = gameplay.Descendants("Compile").Select(c => c.Attribute("Include")!.Value).ToList();
        Assert.Equal([Path.Combine(project, "Assets", "Game", "Gameplay", "DamageZone.cs")], compile.Select(Path.GetFullPath));
        Assert.Equal(["Game.Core.csproj"], gameplay.Descendants("ProjectReference").Select(p => p.Attribute("Include")!.Value));
        Assert.Empty(core.Descendants("ProjectReference"));

        var references = gameplay.Descendants("Reference").ToDictionary(r => r.Attribute("Include")!.Value, r => r.Element("HintPath")!.Value);
        Assert.Contains("UnityEngine.CoreModule", references.Keys);
        Assert.Contains("netstandard", references.Keys);
        Assert.Contains("UnityEditor.CoreModule", references.Keys);
        Assert.All(references.Values, p => Assert.True(Path.IsPathRooted(p) && File.Exists(p), p));

        Assert.Equal(["Game.Core.csproj", "Game.Gameplay.csproj"], solution.Root!.Elements("Project").Select(p => p.Attribute("Path")!.Value));
    }

    /// <summary>--out inside a protected folder is refused before anything is written.</summary>
    [Theory]
    [InlineData("Assets")]
    [InlineData("Packages")]
    [InlineData("ProjectSettings")]
    public void Out_inside_protected_folder_is_refused(string folder)
    {
        using var temp = new TempDir();
        var project = Path.Combine(temp.Path, "p");
        TempDir.Copy(Path.Combine(Repo.Fixtures, "asmdef-ref-by-name"), project);
        var outDir = Path.Combine(project, folder, "ide");

        var (exit, _, stderr) = Cli.Run(new TestEnvironment(temp.Path), "export-csproj", project, "--out", outDir);

        Assert.Equal(3, exit);
        Assert.Contains($"inside {folder}/", stderr, StringComparison.Ordinal);
        Assert.False(Directory.Exists(outDir));
    }

    /// <summary>--out is required.</summary>
    [Fact]
    public void Missing_out_exit_3()
    {
        using var temp = new TempDir();
        var (exit, _, stderr) = Cli.Run(new TestEnvironment(temp.Path), "export-csproj", temp.Path);
        Assert.Equal(3, exit);
        Assert.Contains("--out", stderr, StringComparison.Ordinal);
    }
}
