<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>PlayerSpikeTests</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(PlayerManaged)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(PlayerManaged)/UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
