using System.Text;
using System.Xml;
using System.Xml.Linq;
using Ucl.Core.Graph;
using Ucl.Discovery;

namespace Ucl.Cli;

/// <summary>Builds the SDK-style project files and solution of <c>ucl export-csproj</c>.</summary>
internal static class CsprojWriter
{
    private const string Banner =
        " Generated by `ucl export-csproj` for IDEs. ucl itself never reads this file; regenerate it instead of editing. ";

    /// <summary>The project file of one assembly.</summary>
    /// <param name="plan">The assembly.</param>
    /// <param name="graph">Its cell's graph (for the .NET profile and sibling assemblies).</param>
    /// <param name="project">Maps logical paths to disk.</param>
    /// <param name="editorReferences">Absolute paths of the editor and profile DLLs.</param>
    public static byte[] Project(AssemblyPlan plan, AssemblyGraph graph, ProjectContext project, IReadOnlyList<string> editorReferences)
    {
        var props = new XElement("PropertyGroup",
            new XElement("TargetFramework", plan.NetFramework ? "net48" : "netstandard2.1"),
            new XElement("AssemblyName", plan.Name),
            new XElement("EnableDefaultItems", "false"),
            new XElement("EnableDefaultCompileItems", "false"),
            new XElement("LangVersion", plan.LangVersion),
            new XElement("Nullable", plan.Nullable),
            new XElement("AllowUnsafeBlocks", plan.AllowUnsafe ? "true" : "false"),
            new XElement("DefineConstants", string.Join(';', plan.Defines.Symbols.Order(StringComparer.Ordinal))),
            new XElement("NoWarn", string.Join(';', plan.NoWarn)),

            // Unity's own reference assemblies are the whole framework: nothing implicit from the SDK may leak in.
            new XElement("NoStdLib", "true"),
            new XElement("DisableImplicitFrameworkReferences", "true"),
            new XElement("ImplicitUsings", "disable"),
            new XElement("GenerateAssemblyInfo", "false"),
            new XElement("GenerateTargetFrameworkAttribute", "false"));
        if (plan.WarnAsErrorAll)
        {
            props.Add(new XElement("TreatWarningsAsErrors", "true"));
        }

        if (plan.WarnAsErrorIds.Count > 0)
        {
            props.Add(new XElement("WarningsAsErrors", string.Join(';', plan.WarnAsErrorIds)));
        }

        if (plan.WarnNotAsErrorIds.Count > 0)
        {
            props.Add(new XElement("WarningsNotAsErrors", string.Join(';', plan.WarnNotAsErrorIds)));
        }

        var compile = new XElement("ItemGroup", plan.Sources.Select(s => new XElement("Compile", new XAttribute("Include", project.ToPhysical(s)))));

        // Display names collide across folders (netstandard facades and shims); the first path, in compiler order, wins.
        var dlls = editorReferences.Concat(plan.PrecompiledReferences.Select(project.ToPhysical))
            .DistinctBy(p => Path.GetFileNameWithoutExtension(p), StringComparer.OrdinalIgnoreCase);
        var references = new XElement("ItemGroup", dlls.Select(p => new XElement("Reference",
            new XAttribute("Include", Path.GetFileNameWithoutExtension(p)),
            new XElement("HintPath", p),
            new XElement("Private", "false"))));
        var siblings = new XElement("ItemGroup", plan.References
            .Where(r => graph.Find(r) is not null)
            .Select(r => new XElement("ProjectReference", new XAttribute("Include", $"{r}.csproj"))));
        var analyzers = new XElement("ItemGroup", plan.Analyzers.Select(a => new XElement("Analyzer", new XAttribute("Include", project.ToPhysical(a)))));
        var additional = new XElement("ItemGroup",
            plan.AdditionalFiles.Select(a => new XElement("AdditionalFiles", new XAttribute("Include", project.ToPhysical(a)))),
            plan.AnalyzerConfigs.Select(a => new XElement("EditorConfigFiles", new XAttribute("Include", project.ToPhysical(a)))));

        var root = new XElement("Project", new XAttribute("Sdk", "Microsoft.NET.Sdk"), props, compile);
        foreach (var group in new[] { references, siblings, analyzers, additional }.Where(g => g.HasElements))
        {
            root.Add(group);
        }

        return Serialize(new XDocument(new XComment(Banner), root));
    }

    /// <summary>The <c>.slnx</c> that lists the generated projects.</summary>
    public static byte[] Solution(IEnumerable<string> assemblyNames) =>
        Serialize(new XDocument(
            new XComment(Banner),
            new XElement("Solution", assemblyNames.Select(n => new XElement("Project", new XAttribute("Path", $"{n}.csproj"))))));

    private static byte[] Serialize(XDocument doc)
    {
        using var stream = new MemoryStream();
        var settings = new XmlWriterSettings { Indent = true, OmitXmlDeclaration = true, Encoding = new UTF8Encoding(false), NewLineChars = "\n" };
        using (var writer = XmlWriter.Create(stream, settings))
        {
            doc.Save(writer);
        }

        stream.WriteByte((byte)'\n');
        return stream.ToArray();
    }
}
